language: generic
compiler: gcc
dist: bionic


addons:
    apt:
        packages:
            - libxkbcommon-x11-0
            - libgl1-mesa-dev

services: 
    - xvfb

env:
    - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH="$TRAVIS_BUILD_DIR/Qt/5.13.2/gcc_64/bin:${PATH}"


install:
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

# Xenial
services:
  - xvfb

# Trusty
# Start virtual X server
# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script:
  - git clone https://github.com/benlau/qtci.git
  - source qtci/path.env
  - install-qt 5.14
  - qmake --version
  - qmake
  - make
  - ./travis_ci_qt5
